---
# AWS IoT Greengrass code snippet examples
files:
  - path: snippets/connector_cloudwatch_metrics_usage.py
    services:
      - greengrass
  - path: snippets/connector_image_classification_usage.py
    services:
      - greengrass
  - path: snippets/connector_kinesis_firehose_usage.py
    services:
      - greengrass
  - path: snippets/connector_modbus_rtu_usage.py
    services:
      - greengrass
  - path: snippets/connector_raspberrypi_gpio_usage.py
    services:
      - greengrass
  - path: snippets/connector_serial_stream_usage.py
    services:
      - greengrass
  - path: snippets/connector_servicenow_metricsbase_integration_usage.py
    services:
      - greengrass
  - path: snippets/connector_sns_usage.py
    services:
      - greengrass
  - path: snippets/connector_splunk_integration_usage.py
    services:
      - greengrass
  - path: snippets/connector_twilio_notifications_usage.py
    services:
      - greengrass
  - path: snippets/getting_started_connectors.py
    services:
      - greengrass
  - path: snippets/iot_data_client_boto3.py
    services:
      - greengrass
  - path: snippets/iot_data_client_greengrasssdk.py
    services:
      - greengrass
  - path: snippets/local_resource_access_volume.py
    services:
      - greengrass
  - path: snippets/secret_resource_access.py
    services:
      - greengrass
  - path: snippets/secret_resource_access_default_value.py
    services:
      - greengrass
  - path: snippets/secret_resource_access_staging_label.py
    services:
      - greengrass
  - path: test/test_greengrass_snippets.py
    services:
      - greengrass
