---
# AWS Step Functions state machines example.
files:
  - path: state_definitions.py
    services:
      - stepfunctions
  - path: stepfunctions_basics.py
    services:
      - stepfunctions
  - path: stepfunctions_demo.py
    services:
      - dynamodb
      - lambda
      - sqs
      - stepfunctions
  - path: test/conftest.py
    services:
      - stepfunctions
  - path: test/test_stepfunctions_basics.py
    services:
      - stepfunctions
...