---
# Amazon Comprehend examples
files:
  - path: comprehend_classifier.py
    services:
      - comprehend
  - path: comprehend_classifier_demo.py
    services:
      - comprehend
  - path: comprehend_demo_resources.py
    services:
      - comprehend
  - path: comprehend_detect.py
    services:
      - comprehend
  - path: comprehend_topic_modeler.py
    services:
      - comprehend
  - path: comprehend_topic_modeler_demo.py
    services:
      - comprehend
  - path: test/conftest.py
    services:
      - comprehend
  - path: test/test_comprehend_classifier.py
    services:
      - comprehend
  - path: test/test_comprehend_classifier_demo.py
    services:
      - comprehend
  - path: test/test_comprehend_demo_resources.py
    services:
      - comprehend
  - path: test/test_comprehend_detect.py
    services:
      - comprehend
  - path: test/test_comprehend_topic_modeler.py
    services:
      - comprehend
...
