---
# Amazon CloudWatch custom metrics and alarms example
files:
  - path: cloudwatch_basics.py
    services:
      - cloudwatch
  - path: test/conftest.py
    services:
      - cloudwatch
  - path: test/test_cloudwatch_basics.py
    services:
      - cloudwatch
...
