# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# This AWS CloudFormation template creates the following AWS resources:
#
# * A bucket in Amazon Simple Storage Service (Amazon S3).
#
# You can run this app instead of running equivalent AWS SDK for Ruby
# code examples elsewhere in this directory, such as:
#
# * create_bucket_snippet.rb
# * s3_ruby_create_bucket.rb
# * s3-ruby-example-create-bucket.rb
#
# You can run this template in a few different ways:
#
# 1. To run this template with the AWS Command Line Interface (AWS CLI):
#
#    aws cloudformation create-stack --template-body file://s3-ruby-example-create-bucket.yaml --stack-name S3RubyExampleCreateBucketStack
#
#    This will create a stack in AWS CloudFormation. This stack will create
#    the specified AWS resources.
#
#    To display the names of the generated resources, run the following command:
#
#    aws cloudformation describe-stacks --stack-name S3RubyExampleCreateBucketStack --query Stacks[0].Outputs --output text
#
#    Note that the generated resources might not be immediately available.
#    You can keep running this command until their names are displayed.
#
#    To destroy the generated AWS resources after you are finished using them,
#    run the following command:
#
#    aws cloudformation delete-stack --stack-name S3RubyExampleCreateBucketStack
#
# 2. To run this template with the AWS CloudFormation console, sign in at:
#
#    https://console.aws.amazon.com/cloudformation
#
#    Choose Create stack, and then follow
#    the on-screen instructions to create a stack in AWS CloudFormation
#    based on this template. This stack will create the specified AWS resources.
#
#    The names of the generated resources will display on the stack's
#    Outputs tab in the console after the stack's status displays as
#    CREATE_COMPLETE.
#
#    To destroy the generated AWS resources after you are finished using them,
#    choose the stack in the console, choose Delete, and then follow
#    the on-screen instructions.
#
# This file was generated from an AWS Cloud Development Kit (AWS CDK) app at:
#
# https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/resources/cdk/s3-ruby-example-create-bucket

Resources:
  bucket43879C71:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: S3RubyExampleCreateBucketStack/bucket/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.87.1,@aws-cdk/aws-events=1.87.1,@aws-cdk/aws-iam=1.87.1,@aws-cdk/aws-kms=1.87.1,@aws-cdk/aws-s3=1.87.1,@aws-cdk/cloud-assembly-schema=1.87.1,@aws-cdk/core=1.87.1,@aws-cdk/cx-api=1.87.1,@aws-cdk/region-info=1.87.1,jsii-runtime=node.js/v15.3.0
    Metadata:
      aws:cdk:path: S3RubyExampleCreateBucketStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  BucketName:
    Value:
      Ref: bucket43879C71
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

