---
# AWS Certificate Manager (ACM) basic usage examples
files:
  - path: certificate_basics.py
    services:
      - acm
  - path: test/conftest.py
    services:
      - acm
  - path: test/test_certificate_basics.py
    services:
      - acm
...
