---
# AWS Secrets Manager example.
files:
  - path: secretsmanager_basics.py
    services:
      - rds-data
      - secretsmanager
  - path: test\conftest.py
    services:
      - secretsmanager
  - path: test\test_secretsmanager_basics.py
    services:
      - secretsmanager
...