---
# Amazon Aurora lending library example
files:
  - path: lending_library/library_demo.py
    services:
      - chalice
      - rds
      - rds-data
      - secretsmanager
  - path: lending_library/library_api/app.py
    services:
      - chalice
  - path: lending_library/library_api/chalicelib/library_data.py
    services:
      - rds
      - rds-data
      - secretsmanager
  - path: lending_library/library_api/chalicelib/mysql_helper.py
    services:
      - rds
  - path: lending_library/library_api/chalicelib/__init__.py
    services:
      - rds
  - path: lending_library/library_api/test/conftest.py
    services:
      - rds
  - path: lending_library/library_api/test/test_library_api_app.py
    services:
      - chalice
  - path: lending_library/library_api/test/test_library_data.py
    services:
      - rds
      - rds-data
      - secretsmanager
  - path: lending_library/library_api/test/test_mysql_helper.py
    services:
      - rds
  - path: lending_library/rds_tools/aurora_tools.py
    services:
      - rds
      - secretsmanager
  - path: lending_library/rds_tools/test/conftest.py
    services:
      - rds
  - path: lending_library/rds_tools/test/test_aurora_tools.py
    services:
      - rds
      - secretsmanager
...