---
# Amazon Kinesis streams usage example
files:
  - path: streams/dg_anomaly.py
    services:
      - kinesis
  - path: streams/dg_anomalyex.py
    services:
      - kinesis
  - path: streams/dg_columnlog.py
    services:
      - kinesis
  - path: streams/dg_hotspots.py
    services:
      - kinesis
  - path: streams/dg_referrer.py
    services:
      - kinesis
  - path: streams/dg_regexlog.py
    services:
      - kinesis
  - path: streams/dg_stagger.py
    services:
      - kinesis
  - path: streams/dg_stockticker.py
    services:
      - kinesis
  - path: streams/dg_tworecordtypes.py
    services:
      - kinesis
  - path: streams/dg_weblog.py
    services:
      - kinesis
  - path: streams/kinesis_stream.py
    services:
      - kinesis
  - path: test/conftest.py
    services:
      - kinesis
  - path: test/test_data_generators.py
    services:
      - kinesis
  - path: test/test_kinesis_stream.py
    services:
      - kinesis
...
---
# Amazon Kinesis Data Analytics v2 usage example
files:
  - path: kinesisanalyticsv2_demo.py
    services:
      - kinesisanalyticsv2
  - path: analyticsv2/analytics_application.py
    services:
      - kinesisanalyticsv2
  - path: test/test_analytics_application.py
    services:
      - kinesisanalyticsv2
...
