---
# Amazon Rekognition image and video detection example.
files:
  - path: rekognition_collections.py
    services:
      - rekognition
  - path: rekognition_image_detection.py
    services:
      - rekognition
  - path: rekognition_objects.py
    services:
      - rekognition
  - path: rekognition_video_detection.py
    services:
      - rekognition
  - path: test\conftest.py
    services:
      - rekognition
  - path: test\test_rekognition_collections.py
    services:
      - rekognition
  - path: test\test_rekognition_image_detection.py
    services:
      - rekognition
  - path: test\test_rekognition_video_detection.py
    services:
      - rekognition
...